#file: noinspection SpellCheckingInspection

name: CI-Android APK

env:
  main_project_module: app
  playstore_name: Beans

on:
  push:
    branches: [ main ]
    tags:
      - '**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build Debug APK
        run: |
          VERSION_CODE=$(git rev-list --count HEAD)
          VERSION_NAME=$(git describe --tags --always)
          ./gradlew assembleDebug -PVERSION_CODE=$VERSION_CODE -PVERSION_NAME=$VERSION_NAME

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: Cowspent-debug
          path: app/build/outputs/apk/debug/*.apk